/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2014 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

int init_proc();
// void setbuf(FILE *stream, char *buf);
// ssize_t read(int fd, void *buf, size_t nbytes);
// int puts(const char *s);
// int __gmon_start__(void); weak
// void exit(int status);
// ssize_t write(int fd, const void *buf, size_t n);
// void *memset(void *s, int c, size_t n);
void _x86_get_pc_thunk_bx();
signed int deregister_tm_clones();
int register_tm_clones();
signed int _do_global_dtors_aux();
int frame_dummy();
int dovuln();
int __cdecl main(int argc, const char **argv, const char **envp);
int _libc_csu_init();
void term_proc();

//-------------------------------------------------------------------------
// Data declarations

int (*_frame_dummy_init_array_entry[2])() = { &frame_dummy, &_do_global_dtors_aux }; // weak
int (*_do_global_dtors_aux_fini_array_entry)() = &_do_global_dtors_aux; // weak
char wel[22] = "Plz input something:\n"; // weak
FILE *stderr; // idb
FILE *stdin; // idb
FILE *stdout; // idb
char completed_7181; // weak
// extern _UNKNOWN _gmon_start__; weak


//----- (08048408) --------------------------------------------------------
int init_proc()
{
  int result; // eax@1

  result = (int)&_gmon_start__;
  if ( &_gmon_start__ )
    result = __gmon_start__();
  return result;
}
// 8048480: using guessed type int __gmon_start__(void);

//----- (080484D0) --------------------------------------------------------
#error "80484D3: positive sp value has been found (funcsize=2)"

//----- (08048500) --------------------------------------------------------
void _x86_get_pc_thunk_bx()
{
  ;
}

//----- (08048510) --------------------------------------------------------
signed int deregister_tm_clones()
{
  return 3;
}
// 8048510: could not find valid save-restore pair for ebp

//----- (08048540) --------------------------------------------------------
int register_tm_clones()
{
  return 0;
}
// 8048540: could not find valid save-restore pair for ebp

//----- (08048580) --------------------------------------------------------
signed int _do_global_dtors_aux()
{
  signed int result; // eax@2

  if ( !completed_7181 )
  {
    result = deregister_tm_clones();
    completed_7181 = 1;
  }
  return result;
}
// 8048580: could not find valid save-restore pair for ebp
// 804A088: using guessed type char completed_7181;

//----- (080485A0) --------------------------------------------------------
int frame_dummy()
{
  return register_tm_clones();
}
// 80485A0: could not find valid save-restore pair for ebp

//----- (080485CB) --------------------------------------------------------
int dovuln()
{
  int v0; // eax@5
  int result; // eax@6
  int v2; // ecx@6
  char buf; // [sp+4h] [bp-44h]@2
  char v4[51]; // [sp+5h] [bp-43h]@1
  int v5; // [sp+38h] [bp-10h]@1
  int v6; // [sp+3Ch] [bp-Ch]@1

  v6 = *MK_FP(__GS__, 20);
  memset(v4, 0, 0x30u);
  v5 = 0;
  while ( 1 )
  {
    if ( read(0, &buf, 1u) != 1 )
      exit(0);
    if ( buf == 10 )
      break;
    v0 = v5++;
    v4[v0] = buf;
  }
  result = puts(v4);
  v2 = *MK_FP(__GS__, 20) ^ v6;
  return result;
}
// 80485CB: using guessed type char var_43[51];

//----- (0804865C) --------------------------------------------------------
int __cdecl main(int argc, const char **argv, const char **envp)
{
  setbuf(stdin, 0);
  setbuf(stdout, 0);
  setbuf(stderr, 0);
  write(1, wel, 0x1Eu);
  dovuln();
  return 0;
}

//----- (080486D0) --------------------------------------------------------
int _libc_csu_init()
{
  int v0; // edi@1
  int result; // eax@1
  signed int v2; // esi@1

  v0 = 0;
  init_proc();
  result = (int)_frame_dummy_init_array_entry;
  v2 = &_do_global_dtors_aux_fini_array_entry - _frame_dummy_init_array_entry;
  if ( v2 )
  {
    do
      result = _frame_dummy_init_array_entry[v0++]();
    while ( v0 != v2 );
  }
  return result;
}
// 8049F08: using guessed type int (*_frame_dummy_init_array_entry[2])();
// 8049F0C: using guessed type int (*_do_global_dtors_aux_fini_array_entry)();

//----- (08048734) --------------------------------------------------------
void term_proc()
{
  ;
}

#error "There were 1 decompilation failure(s) on 11 function(s)"
